galaxy_info:
  role_name: lamp
  author: OT-OSM
  description: LAMP Stack Role
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
dependencies: []
