---
- name: Install MySQL packages
  ansible.builtin.apt:
    name: "{{ mysql_packages }}"
    state: present

- name: Ensure MySQL is started and enabled
  ansible.builtin.systemd:
    name: "{{ mysql_service }}"
    state: started
    enabled: true
  notify: restart mysql
